# Generated by Django 6.1 on 2026-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_score', models.FloatField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
