# Generated by Django 6.1 on 2026-08-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='driver_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_matches', to='routes.route'),
        ),
        migrations.AddField(
            model_name='match',
            name='rider_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_matches', to='routes.route'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('driver_route', 'rider_route')},
        ),
    ]
