import { useMemo, useState } from 'react'
import { Calculator, Fuel } from 'lucide-react'

export default function CostSplit() {
  const [distance, setDistance] = useState('')
  const [riders, setRiders] = useState('2')
  const [costPerKm, setCostPerKm] = useState('30')
  const result = useMemo(() => { const d = Number(distance); const r = Number(riders); const c = Number(costPerKm); return d > 0 && r > 0 && c >= 0 ? (d * c) / r : 0 }, [distance, riders, costPerKm])
  return <div className="mx-auto max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-600"><Calculator size={18} /></div><div><h2 className="text-lg font-bold text-slate-800">Cost split calculator</h2><p className="text-xs text-slate-400">Estimate a fair contribution based on distance and the number of riders.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div><label className="text-xs font-semibold text-slate-500">Distance (km)</label><input type="number" min="0" step="0.1" value={distance} onChange={(e) => setDistance(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400" /></div><div><label className="text-xs font-semibold text-slate-500">Number of riders</label><input type="number" min="1" value={riders} onChange={(e) => setRiders(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400" /></div><div><label className="text-xs font-semibold text-slate-500">PKR per km</label><input type="number" min="0" value={costPerKm} onChange={(e) => setCostPerKm(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400" /></div></div><div className="mt-6 rounded-2xl bg-gradient-to-r from-emerald-50 to-cyan-50 p-5"><div className="flex items-center gap-2 text-emerald-600"><Fuel size={16} /><span className="text-xs font-semibold">Estimated cost per rider</span></div><p className="mt-2 text-3xl font-bold text-slate-800">PKR {result.toFixed(2)}</p><p className="mt-1 text-[11px] text-slate-400">Final trip costs may vary depending on the agreed ride details.</p></div></div>
}
