import { useEffect, useState } from 'react'
import { Car, CheckCircle2, Gauge, IdCard } from 'lucide-react'
import { usersApi, apiErrorMessage } from '../lib/api.js'
import { ErrorState, LoadingState } from '../components/common/AsyncState.jsx'
import { useAuth } from '../context/AuthContext.jsx'

export default function DriverProfile() {
  const { user, updateSessionUser } = useAuth()
  const [profile, setProfile] = useState(null)
  const [form, setForm] = useState({ car_model: '', plate_number: '', seats_available: 4 })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { usersApi.driverProfile().then(({ data }) => setProfile(data)).catch((err) => { if (err.response?.status !== 404) setError(apiErrorMessage(err)) }).finally(() => setLoading(false)) }, [])
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const { data } = await usersApi.createDriverProfile({ ...form, seats_available: Number(form.seats_available) }); setProfile(data); updateSessionUser({ id: data.user || user.id, driver_profile: data }) } catch (err) { setError(apiErrorMessage(err, 'Could not create driver profile.')) } finally { setSaving(false) } }
  if (loading) return <LoadingState label="Loading driver profile…" />
  if (profile) return <div className="mx-auto max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-600"><CheckCircle2 size={20} /></div><div><h2 className="text-lg font-bold text-slate-800">Driver profile active</h2><p className="text-xs text-slate-400">Your vehicle information is ready for upcoming rides.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><Car size={16} className="text-violet-500" /><p className="mt-2 text-sm font-semibold text-slate-700">{profile.car_model}</p><p className="text-[10px] text-slate-400">Car model</p></div><div className="rounded-xl bg-slate-50 p-4"><IdCard size={16} className="text-indigo-500" /><p className="mt-2 text-sm font-semibold text-slate-700">{profile.plate_number}</p><p className="text-[10px] text-slate-400">Plate number</p></div><div className="rounded-xl bg-slate-50 p-4"><Gauge size={16} className="text-cyan-500" /><p className="mt-2 text-sm font-semibold text-slate-700">{profile.seats_available}</p><p className="text-[10px] text-slate-400">Seats available</p></div></div><p className="mt-5 text-xs leading-5 text-slate-400">Your driver profile helps riders identify your vehicle and available seating.</p></div>
  return <form onSubmit={submit} className="mx-auto max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-800">Create driver profile</h2><p className="mt-1 text-xs text-slate-400">Required before offering seats as a driver.</p>{error && <div className="mt-4"><ErrorState message={error} /></div>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="text-xs font-semibold text-slate-500">Car model</label><input required value={form.car_model} onChange={(e) => setForm({ ...form, car_model: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400" /></div><div><label className="text-xs font-semibold text-slate-500">Plate number</label><input required value={form.plate_number} onChange={(e) => setForm({ ...form, plate_number: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400" /></div><div><label className="text-xs font-semibold text-slate-500">Seats available</label><select value={form.seats_available} onChange={(e) => setForm({ ...form, seats_available: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{[1,2,3,4,5,6,7].map((n) => <option key={n} value={n}>{n}</option>)}</select></div></div><button disabled={saving} className="mt-5 w-full rounded-xl bg-violet-600 py-3 text-sm font-semibold text-white">{saving ? 'Saving…' : 'Create driver profile'}</button></form>
}
